Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - . ./prepare-and-run-flake8.sh "$CI_PROJECT_NAME" examples
  tags:
  - python3
  except:
  - tags

Documentation:
  script: |
    EXTRA_INSTALL="numpy"
    curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/ci-support.sh
    . ./ci-support.sh
    build_py_project_in_venv
    build_docs --no-check
  tags:
  - python3
