Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - . ./prepare-and-run-flake8.sh "$CI_PROJECT_NAME" test examples
  tags:
  - python3
  except:
  - tags

Python 3:
  script: |
    sudo apt update
    sudo apt install libsilo-dev
    ./configure.py --use-silo
    EXTRA_INSTALL="numpy pybind11"
    curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
    . ./build-and-test-py-project.sh
  tags:
  - docker-runner
  except:
  - tags
  artifacts:
    reports:
      junit: test/pytest.xml

Examples:
  script: |
    sudo apt update
    sudo apt install libsilo-dev

    # not expected to run without matplotlib and vtk
    rm examples/vtk-sample-elements.py

    ./configure.py --use-silo
    EXTRA_INSTALL="numpy pybind11"
    curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/ci-support.sh
    . ./ci-support.sh
    build_py_project_in_venv
    run_examples
  tags:
  - docker-runner
  except:
  - tags

Documentation:
  script: |
    EXTRA_INSTALL="numpy"
    curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/ci-support.sh
    . ./ci-support.sh
    build_py_project_in_venv
    build_docs
    maybe_upload_docs
  tags:
  - python3
