name: CI
on:
    push:
        branches:
        - master
    pull_request:
    schedule:
        - cron:  '17 3 * * 0'

jobs:
    flake8:
        name: Flake8
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: '3.x'
        -   name: "Main Script"
            run: |
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
                . ./prepare-and-run-flake8.sh  "$(basename $GITHUB_REPOSITORY)" test examples

    pytest:
        name: Pytest on Py${{ matrix.python-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.6, 3.x]
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: ${{ matrix.python-version }}
        -   name: "Main Script"
            run: |
                ./.ci/install-silo-on-github.sh
                EXTRA_INSTALL="numpy pybind11"
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/ci-support.sh
                . ./ci-support.sh
                ./configure.py --use-silo
                build_py_project_in_venv
                test_py_project

    examples:
        name: Examples on Py${{ matrix.python-version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.6, 3.x]
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: ${{ matrix.python-version }}
        -   name: "Main Script"
            run: |
                # not expected to run without matplotlib and vtk
                rm examples/vtk-sample-elements.py

                ./.ci/install-silo-on-github.sh
                EXTRA_INSTALL="numpy pybind11"
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/ci-support.sh
                . ./ci-support.sh
                ./configure.py --use-silo
                build_py_project_in_venv
                run_examples

    docs:
        name: Documentation
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -
            uses: actions/setup-python@v1
            with:
                python-version: '3.x'
        -   name: "Main Script"
            run: |
                ./.ci/install-silo-on-github.sh
                EXTRA_INSTALL="numpy pybind11"
                curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/ci-support.sh
                . ./ci-support.sh
                ./configure.py --use-silo
                build_py_project_in_venv
                build_docs

# vim: sw=4
